FROM nginx:mainline
RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_14.x  | bash -
RUN apt-get -y install nodejs
WORKDIR /var/www/opentravian
#RUN npm install